// client/homebank-client/src/budgets/budget-list/BudgetList.tsx
import React from 'react';
import {groupBy} from '../../shared/functions/groupBy';
import {BudgetModel} from '../budget/budget.model';
import './BudgetList.scss';

export interface BudgetListProps {
  budgets: BudgetModel[];
}

export const BudgetList: React.FunctionComponent<BudgetListProps> = (props: BudgetListProps) => {
  const categoriesPerGroup = groupBy(props.budgets, budget => budget.categoryGroupName);

  return (
    <div>
      <div className="budget-table">
        <div className="budget-table__row budget-table__row--header">
          <div className="budget-table__category-column">Category</div>
          <div className="budget-table__column">Budgeted</div>
          <div className="budget-table__column">Activity</div>
          <div className="budget-table__column">Available</div>
        </div>
        {Object.keys(categoriesPerGroup).map((key: string) => {
          const rows = [];

          rows.push(
            <div key={key} className="budget-table__row budget-table__row--category-group">
              <div data-label="Category" className="budget-table__category-group-column">
                {key}
              </div>
              <div data-label="Budgeted" className="budget-table__column">
                <div>0</div>
              </div>
              <div data-label="Activity" className="budget-table__column">
                <div>0</div>
              </div>
              <div data-label="Available" className="budget-table__column">
                <div>0</div>
              </div>
            </div>
          );

          categoriesPerGroup[key].forEach((budget: BudgetModel) => {
            rows.push(
              <div key={budget.categoryId} className="budget-table__row">
                <div data-label="Category" className="budget-table__category-column">
                  <div>{budget.categoryName}</div>
                </div>
                <div data-label="Budgeted" className="budget-table__column">
                  <div>{budget.budgeted}</div>
                </div>
                <div data-label="Activity" className="budget-table__column">
                  <div>{budget.activity}</div>
                </div>
                <div data-label="Available" className="budget-table__column">
                  <div>{budget.available}</div>
                </div>
              </div>
            );
          });

          return rows;
        })}
      </div>

      {/* {Object.keys(categoriesPerGroup).map((key: string, index: number) => {
        return (
          <table className="table budget-table" key={key}>
            <colgroup>
              <col className="budget-table__category-column" />
              <col className="budget-table__column" />
              <col className="budget-table__column" />
              <col className="budget-table__column" />
            </colgroup>
            <thead>
              <tr>
                <th>{key}</th>
                <th>0</th>
                <th>0</th>
                <th>0</th>
              </tr>
            </thead>
            <tbody>
              {categoriesPerGroup[key].map((budget: BudgetModel) => {
                return (
                  <tr key={budget.categoryId}>
                    <td>{budget.categoryName}</td>
                    <td>{budget.budgeted}</td>
                    <td>{budget.activity}</td>
                    <td>{budget.available}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        );
      })} */}
    </div>
  );
};

// client/thuisbank/src/app/features/budgets/budget-list/budget-list.component.ts
import {Component, OnInit} from '@angular/core';
import * as _ from 'lodash';
import {Store, select} from '@ngrx/store';
import {BudgetModel, BudgetPerGroupModel} from '../shared/budget.model';
import {Observable} from 'rxjs';
import {map} from 'rxjs/operators';

@Component({
  selector: 'app-budget-list',
  templateUrl: './budget-list.component.html',
  styleUrls: ['./budget-list.component.css'],
})
export class BudgetListComponent implements OnInit {
  public budget$: Observable<BudgetPerGroupModel[]>;

  constructor(store: Store<{budgets: BudgetModel[]}>) {
    this.budget$ = store.pipe(
      select(state => state.budgets),
      map(this.groupBudgetItemsByGroup)
    );
  }

  private groupBudgetItemsByGroup(budgetItems: BudgetModel[]): BudgetPerGroupModel[] {
    return _.chain(budgetItems)
      .groupBy(budget => budget.categoryGroupName)
      .map(
        (budgetsForGroup, categoryGroupName) =>
          ({categoryGroupName, budgets: budgetsForGroup} as BudgetPerGroupModel)
      )
      .value();
  }

  ngOnInit() {}
}

<app-budget-header></app-budget-header>

<div *ngIf="budget$ | async as budgetsPerGroup">
  <div class="budget-table">
    <div class="budget-table__row budget-table__row--header">
      <div class="budget-table__category-column budget-table__category-column--small-font">
        Category
      </div>
      <div class="budget-table__column">Budgeted</div>
      <div class="budget-table__column">Activity</div>
      <div class="budget-table__column">Available</div>
    </div>

    <div
      *ngFor="let categoryGroup of budgetsPerGroup"
      [attr.data-test-id]="categoryGroup.categoryGroupName"
      class="budget-table__row budget-table__row--category-group"
    >
      <div data-label="Category" class="budget-table__category-group-column">
        {{ categoryGroup.categoryGroupName }}
      </div>
      <div data-label="Budgeted" class="budget-table__column">
        <!-- <div>{formatToCurrency(0)}</div> -->
        <span>0</span>
      </div>
      <div data-label="Activity" class="budget-table__column">
        <span>0</span>
      </div>
      <div data-label="Available" class="budget-table__column">
        <span>0</span>
      </div>
    </div>
  </div>
</div>

<p>
  budget-list works!
</p>
